FROM node:17.8-alpine3.14 AS BUILD_IMAGE

WORKDIR /app

COPY package*.json ./

RUN npm ci

FROM node:17.8-alpine3.14

WORKDIR /usr/src/app

COPY --from=BUILD_IMAGE /app .
COPY . .

CMD ["node_modules/ts-node-dev/lib/bin.js", "--transpile-only", "src/server.ts"]