name: Test e2e
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build deps
        run: |
          sudo apt update && sudo apt upgrade -y
          sudo apt install -y protobuf-compiler libprotobuf-dev
      - name: Build and install
        run: npm i
      - name: Test
        run: npm run test
