name: Build and deploy to DockerHub
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2.1.0
        with:
          platforms: arm64
      - uses: docker/setup-buildx-action@v2.2.0
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build deps
        run: |
          sudo apt update && sudo apt upgrade -y
          sudo apt install -y protobuf-compiler libprotobuf-dev
      - name: build image amd64
        run: |
          docker buildx build \
            --memory="2g" \
            -t a11ywatch/a11ywatch:latest \
            --platform linux/amd64 \
            --push .
      - name: build image arm64
        run: |
          docker buildx build \
            --memory="1.5g" \
            -t a11ywatch/a11ywatch:latest \
            --platform linux/arm64 \
            --push .
