name: github.com/a11ywatch/a11ywatch

on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_SHA: ${{ github.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Dagger
        uses: dagger/dagger-for-github@v3
        with:
          cmds: do test
