name: github.com/a11ywatch/a11ywatch

on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-22.04
    env:
      GITHUB_SHA: ${{ github.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Dagger
        uses: dagger/dagger-for-github@v3
        with:
          install-only: true
      - name: Build deps
        run: |
          sudo apt update && sudo apt upgrade -y
          sudo apt install -y curl
          curl -L https://dl.dagger.io/dagger-cue/install.sh | VERSION=0.2.232 sh
          ./bin/dagger-cue version
      - name: Dagger project update
        run: ./bin/dagger-cue project update
      - name: Dagger do test
        run: ./bin/dagger-cue do test --log-format plain
      # - name: Dagger do deploy
      #   run: dagger do deploy --log-format plain
